### ISSUE TITLE
Enable SSL support

### ISSUE THREAD

**Issue by adutra** [datastax/cassandra-quarkus#111]
If SSL is required to connect, users currently need to add this to their configuration when running in native mode:

```
quarkus.ssl.native=true
```

It would be better to automatically activate SSL support:

```
sslNativeSupport.produce(new ExtensionSslNativeSupportBuildItem(FeatureBuildItem.CASSANDRA));
```

Better yet, this could be done only if we detect that SSL is being required to connect.

In any case, we should then ask the Quarkus team to include Cassandra in the list of extensions supporting SSL automatically [here](https://quarkus.io/guides/native-and-ssl).

This is related to #46.

**Comment by tomekl007** [comment]
For quarkus docs change:
https://github.com/quarkusio/quarkus/pull/11770
