### ISSUE TITLE
Can I use Dao/Mapper for Graph?

### ISSUE THREAD

**Issue by UnvirtualHH** [datastax/cassandra-quarkus#118]
Just a quick question, is it possible to use DAO/Service/Object Mapper also for Graph Queries? Or is it just for "normal" cassandra queries?

**Comment by adutra** [comment]
Hi @UnvirtualHH unfortunately the object mapper does not support graph queries. We have an issue ([JAVA-2858](https://datastax-oss.atlassian.net/browse/JAVA-2858)) to track interest for this feature, feel free to vote for it and comment.

**Comment by UnvirtualHH** [comment]
Ok, no problem. Thanks for the answer. I was just curious if it would work, but it is absolut no problem if not, cause most time I directly use graph output and don't need an object mapper.
