### ISSUE TITLE
Fix wrong code snippet in quickstart guide

### ISSUE THREAD

**Issue by adutra** [datastax/cassandra-quarkus#121]
The [quick start guide](https://quarkus.io/guides/cassandra) has an example where the constructor parameters are in the incorrect order. Notice that STORE_ID should be the first argument:

``` 
  private Fruit convertFromDto(FruitDto fruitDto) {
    return new Fruit(STORE_ID, fruitDto.getName(), fruitDto.getDescription());
  }
``` 

Also the method name has a typo in the online guide.

The github repo version of the doc (cassandra.adoc) is correct. We only need to open a PR against quarkus.io to update the online guide.

**Comment by thomasdarimont** [comment]
The cql statement for creating the `k1.fruits` table is also broken (syntax error) in the readme:
```
docker exec -it local-cassandra-instance cqlsh -e "CREATE TABLE IF NOT EXISTS k1.fruit(store_id text, name text, description text, PRIMARY KEY((store_id), name))"
```

should be
```
docker exec -it local-cassandra-instance cqlsh -e "CREATE TABLE IF NOT EXISTS k1.fruit(store_id text, name text, description text, PRIMARY KEY(store_id, name))"
```
