### ISSUE TITLE
Introduce option for *NOT* connecting to cassandraQL during startup

### ISSUE THREAD

**Issue by JiriOndrusek** [datastax/cassandra-quarkus#124]
I'm working on camel-quarkus extension for CassandraQL (https://github.com/apache/camel-quarkus/issues/1355)

It would be nice to use this quarkus extension.

However there is a problem, which is blocking my attempts. According to the code and quarkus blog, it is necessary to define connection parameters, which are used for connecting to CassabdraQL. 

1. In my case (and I can imagine more scenarios) are connection parameters obtained dynamically. Therefore there is no way of filling application.properties in advance.
2.  In my case (and I can imagine more scenarios) I'd like to connect to several CassandraQLs, which is not possible in case of hardcoded configuration in application.properties.
3. I've noticed a possibility to wait for a default connection in case that target cassandraQL is not available. (attempts for creation of the connection are repeated until there is available connection). But start of the extension is not finished and it is not possible e.g. to connect to other DBs.

IMHO it would be nice, if this extension could start also in some "offline" mode, without connecting to DB. In that case it won't be possible to inject  QuarkusCqlSession. But it would be possible to create similar session(s) programatically

**Comment by adutra** [comment]
Hi thanks for reporting this.

Have you tried disabling eager session initialization? This could be a quick win for you.

https://github.com/datastax/cassandra-quarkus/blob/c6c8b0d1af557bb24b7ff2a185caec065285c6be/runtime/src/main/java/com/datastax/oss/quarkus/runtime/api/config/CassandraClientInitConfig.java#L40

**Comment by JiriOndrusek** [comment]
Thanks @adutra, this seems exactly as a solution for me. I'll try this parameter tomorrow.

**Comment by adutra** [comment]
> In my case (and I can imagine more scenarios) I'd like to connect to several CassandraQLs, which is not possible in case of hardcoded configuration in application.properties.

For that I think we would need to expose the `ProgrammaticDriverConfigLoaderBuilder` bean somehow. We already create this bean internally, see [here](https://github.com/datastax/cassandra-quarkus/blob/b6cf12730bbddf9dd24b2a6dc9a23f1347cc8c8c/runtime/src/main/java/com/datastax/oss/quarkus/runtime/internal/quarkus/CassandraClientProducer.java#L87).

Maybe you could contribute a PR to expose that bean?

**Comment by JiriOndrusek** [comment]
@adutra To be honest, for my case this 'ProgrammaticDriverConfigLoaderBuilder' is not necessary. Once extension for cassandra-quarkus is used, I can use standard code to connect to cassandra using java-driver. Though It could be nice to have it for other use cases... I'll keep that in mind and look into creation of PR if time allows.

**Comment by JiriOndrusek** [comment]
@adutra Parameter `eager-session-init` seems to work only partially.

If parameter is set to false, the I can see in log
>2020-08-25 14:32:22,621 DEBUG [com.dat.oss.qua.run.int.qua.CassandraClientStarter] (main) Not triggering eager initialization of Quarkus session at startup

application does not wait for connection, my tests are executed, **but** once my tests are finished, extension tries to connect again. Which means that my test execution doesn't finish.

I'm attaching trace log with my execution (there is 1 dummy test) and once camel is stopped, connection to cassandra with default values is trying to create.
[trace.log](https://github.com/datastax/cassandra-quarkus/files/5123716/trace.log)

**Comment by adutra** [comment]
I think you just spotted a bug indeed. I need to investigate more, but it seems to come from the fact that we add a shutdown task to close the session, see [here](https://github.com/datastax/cassandra-quarkus/blob/bde8d2bccdd39d058b42542e98348061532bef8c/runtime/src/main/java/com/datastax/oss/quarkus/runtime/internal/quarkus/CassandraClientRecorder.java#L44). I suspect that calling `close()` on an uninitialized proxy triggers the whole initialization procedure, and you end up with that error.

**Comment by tomekl007** [comment]
The other possible solution may be:
https://github.com/datastax/cassandra-quarkus/issues/75

**Comment by JiriOndrusek** [comment]
Hi @tomekl007, 
with parameter `eager-session-init` is exactly solution, which I was trying to get.
Once issue https://github.com/datastax/cassandra-quarkus/issues/125 is closed, from my POV this issue could be closed.

**Comment by tomekl007** [comment]
Closing because it is solved by the `eager-session-init` and https://github.com/datastax/cassandra-quarkus/issues/125.
@JiriOndrusek please let me know if you need any more help.
