### ISSUE TITLE
Any plans to get final?

### ISSUE THREAD

**Issue by UnvirtualHH** [datastax/cassandra-quarkus#140]
Well...obviously the cassandra quarkus project is in Alpha for month...maybe you want to get final sometime?

**Comment by adutra** [comment]
Hi we are planning to release a beta first (probably November). Then a GA should follow in 2021 Q1. Hang tight :-)

**Comment by hellf-ms** [comment]
I don't want to bother you, but it is mid of Jan. 2021 and there is not even a Beta released...

**Comment by adutra** [comment]
Sorry, it's been a crazy time for us these last months. I will work on getting the release done next week or the week after.

**Comment by adutra** [comment]
@UnvirtualHH @hellf-ms 1.0.0 has been released today, please try it out! Apologies for the delay.
