### ISSUE TITLE
Testing of Quarkus Applications with Cassandra

### ISSUE THREAD

**Issue by hellf-ms** [datastax/cassandra-quarkus#142]
I have the problem, always when starting a test and the database is not connected, my test won't run, cause of the app starts to try to connect and runs in a timeout. So the tests will never be executed. 

Do you have a good strategy for testing cassandra applications or better datastax enterprise, cause I also user graph? Is there a testcontainer image for that or maybe other better way?

**Comment by adutra** [comment]
Hi, there is a Cassandra module for TestContainers: https://www.testcontainers.org/modules/databases/cassandra/

It also works with DSE, you only need to create the module with a DSE Docker image. 

DataStax maintains several Docker images that you can use:

* https://hub.docker.com/r/datastax/cassandra
* https://hub.docker.com/r/datastax/dse-server

You can also have a look at this: https://docs.datastax.com/en/docker/doc/docker/dockerQuickStart.html

If you need to integrate TestContainers in a Quarkus test, have a look at our [`CassandraTestResource`](https://github.com/datastax/cassandra-quarkus/blob/master/test-framework/src/main/java/com/datastax/oss/quarkus/test/CassandraTestResource.java).

As for the timeouts in your tests, if you have an example I could take a look.

**Comment by adutra** [comment]
Closing this for now, feel free to re-open if you need further assistance. Thanks!
