### ISSUE TITLE
Increase version of datastax/driver-java to 4.11.1

### ISSUE THREAD

**Issue by yurake** [datastax/cassandra-quarkus#169]
Current version of datastax/driver-java is 4.11.0

It would be great to upgrade newer version because of fixed this PR.
https://github.com/datastax/java-driver/pull/1546

I faced the issue against cassandra-quarkus v1.0.1 and Apache Cassandra v4.
`
15:58:51 WARN  [co.da.os.dr.in.co.co.ControlConnection] (vert.x-eventloop-thread-1) [s0] Error connecting to Node(endPoint=localhost:9042, hostId=null, hashCode=1b90aa60), trying next node (ConnectionInitException: [s0|control|id: 0xc943afaf, L:/127.0.0.1:52677 - R:localhost/127.0.0.1:9042] Protocol initialization request, step 1 (OPTIONS): unexpected failure (java.lang.IllegalArgumentException: Unsupported request opcode: 0 in protocol 6))
`

**Comment by adutra** [comment]
Hi @yurake that's a good idea. In the meanwhile you should be able to override the driver version in your application by importing the driver BOM _before_ the Cassandra client BOM:

```xml
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.datastax.oss</groupId>
            <artifactId>java-driver-bom</artifactId>
            <version>4.11.1</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
        <dependency>
            <groupId>com.datastax.oss.quarkus</groupId>
            <artifactId>cassandra-quarkus-bom</artifactId>
            <version>1.0.1</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-universe-bom</artifactId>
            <version>${quarkus.platform.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```
