### ISSUE TITLE
Upgrade to Quarkus 2.0

### ISSUE THREAD

**Issue by adutra** [datastax/cassandra-quarkus#172]
The extension currently cannot be compiled against Quarkus 2.0, see https://github.com/quarkusio/quarkus/issues/8593#issuecomment-844722003.

Things to fix:

* A few classes do not compile anymore, mostly due to Vert.x API changes.
* MicroProfile 3.0 is not binary-compatible with 2.x; this requires changes in the driver, see [JAVA-2944](https://datastax-oss.atlassian.net/browse/JAVA-2944).
* It turns out that compilation of the extension with Java 11 unveiled Yet-Another-Cryptic-Class-Loading-Problem with the driver's usage of the ServiceLoader API. I opened [JAVA-2946](https://datastax-oss.atlassian.net/browse/JAVA-2946) to fix that (or find a workaround). On the extension side, this is likely to require #171 as well.

**Comment by adutra** [comment]
Also, it would be fair to keep compatibility with Quarkus 1.x and 2.x for some time. I suggest that we keep the 1.0.x series for bugfixes targeting Quarkus 1.x, and create a minor version 1.1.0 along with a new 1.1.x branch to host future improvements and bugfixes targeting Quarkus 2.x.

**Comment by aloubyansky** [comment]
Sounds good.

**Comment by adutra** [comment]
@ppalaga 1.1.0-rc1 is available from Maven Central. Do you need me to upgrade quarkus-platform or can you do it? Thanks!

**Comment by aloubyansky** [comment]
@adutra do you already have a date for the final?

**Comment by aloubyansky** [comment]
Are the tests listed https://github.com/quarkusio/quarkus-platform/blob/main/pom.xml#L248 looking good to you?

**Comment by adutra** [comment]
> @adutra do you already have a date for the final?

We were planning to have our 1.1.0 GA depend on Quarkus 2.0.0.Final. Is that a problem? I guess we are in a classic chicken-and-egg problem :-) 

> Are the tests listed https://github.com/quarkusio/quarkus-platform/blob/main/pom.xml#L248 looking good to you?

Wow this is totally new to me. But yes, the artifacts listed there are 100% correct.

**Comment by aloubyansky** [comment]
> > @adutra do you already have a date for the final?
> 
> We were planning to have our 1.1.0 GA depend on Quarkus 2.0.0.Final. Is that a problem? I guess we are in a classic chicken-and-egg problem :-)

Sure, that makes sense. The Quarkus core 2.0.0.Final release is scheduled on June 23rd and the platform release on June 30th. It'd be great if you could release in time for the platform release.

> > Are the tests listed https://github.com/quarkusio/quarkus-platform/blob/main/pom.xml#L248 looking good to you?
> 
> Wow this is totally new to me. But yes, the artifacts listed there are 100% correct.

Are you subscribed to https://groups.google.com/g/quarkus-platform-coordination ? This is where we announce and coordinate changes and releases. (Also see https://groups.google.com/g/quarkus-platform-coordination/c/NxR3kFzowd0)

**Comment by adutra** [comment]
> The Quarkus core 2.0.0.Final release is scheduled on June 23rd and the platform release on June 30th. It'd be great if you could release in time for the platform release.

That can work, I will plan our release to the 24th.

> Are you subscribed to https://groups.google.com/g/quarkus-platform-coordination ?

In fact I am and I was aware of the changes at hand, only I haven't really payed attention to how things are shaped now.

**Comment by aloubyansky** [comment]
Great, thanks!

**Comment by ppalaga** [comment]
> @ppalaga 1.1.0-rc1 is available from Maven Central. 

Thanks for the release, let me test inside Camel Quarkus first. 

> Do you need me to upgrade quarkus-platform or can you do it?

Sounds like @aloubyansky did it already?

**Comment by aloubyansky** [comment]
> > @ppalaga 1.1.0-rc1 is available from Maven Central.
> 
> Thanks for the release, let me test inside Camel Quarkus first.
> 
> > Do you need me to upgrade quarkus-platform or can you do it?
> 
> Sounds like @aloubyansky did it already?

I haven't.

**Comment by adutra** [comment]
> > > @ppalaga 1.1.0-rc1 is available from Maven Central.
> > 
> > 
> > Thanks for the release, let me test inside Camel Quarkus first.
> > > Do you need me to upgrade quarkus-platform or can you do it?
> > 
> > 
> > Sounds like @aloubyansky did it already?
> 
> I haven't.

Will do it today.

**Comment by ppalaga** [comment]
Any ETA of a release with Quarkus 2.0, @adutra ?
