### ISSUE TITLE
Reactive "if not exists" insertion does not work

### ISSUE THREAD

**Issue by Fabb111** [datastax/cassandra-quarkus#183]
Hello, I am using the newest cassandra-quarkus-client (1.1.0) in combination with resteasy-reactive and kotlin.

I have the following method in my DAO interface:

```kotlin
@Insert(ifNotExists = true)
fun insertIfNotExists(user: User) : Uni<Void>
```

which throws

```
java.lang.IllegalArgumentException: username is not a column in this row
	at com.datastax.oss.driver.internal.core.cql.DefaultRow.firstIndexOf(DefaultRow.java:110)
	at com.datastax.oss.driver.api.core.data.GettableByName.get(GettableByName.java:144)
	at com.datastax.dse.driver.internal.core.cql.reactive.DefaultReactiveRow.get(DefaultReactiveRow.java:260)
...
```

The User model for reference:

```kotlin
@PartitionKey(0)
val username: String,
@PartitionKey(1)
val phrase: String,
val userId: UUID
```

The same happens with

```kotlin
@Insert(ifNotExists = true)
fun insertIfNotExists(user: User) : Uni<Boolean>
```

```kotlin
@Insert(ifNotExists = true)
fun insertIfNotExists(user: User) : MutinyReactiveResultSet
```

```kotlin
@Insert(ifNotExists = true)
fun insertIfNotExists(user: User) : Uni<User?>
```

BUT it works when using one of the official Java driver examples (https://docs.datastax.com/en/developer/java-driver/latest/manual/mapper/daos/insert/).

```kotlin
@Insert(ifNotExists = true)
fun insertIfNotExists(user: User) : User?
```

So not using Mutiny "fixes" the problem. Which would effectively destroy the reactive approach in the whole application.

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/QUAR-2) by [Unito](https://www.unito.io)

**Comment by adutra** [comment]
Hi, I confirm that I can reproduce the issue. It's related to how `MutinyUniResultProducer` determines which exact element type the returned `Uni` should have.

**Comment by adutra** [comment]
Unfortunately the fix would involve removing the Producer + ServiceLoader mechanism and switch to proper compile-time code generation using the existing cassandra-quarkus-mapper-processor module. I will try to allocate some time for it soon.
