### ISSUE TITLE
[JAVA-2794] Reference quarkus extension on code.quarkus.io

### ISSUE THREAD

**Issue by adutra** [datastax/cassandra-quarkus#20]
<p>Imported from <a href="https://datastax-oss.atlassian.net/browse/JAVA-2794">JAVA-2794</a>, originally reported by @adutra on Thu, 28 May 2020 15:56:30 GMT.</p>

**Comment by absurdfarce** [comment]
I _believe_ this will be resolved once we get added to Quarkus Platform.  https://github.com/datastax/cassandra-quarkus/issues/44 aims to address that.

**Comment by tomekl007** [comment]
Our extension is listed on the quarkus.io:
<img width="1221" alt="Screenshot 2020-08-27 at 13 11 59" src="https://user-images.githubusercontent.com/2332235/91435623-e553bd00-e866-11ea-923f-d422907901e6.png">
so I am closing this ticket
