### ISSUE TITLE
Release request for v1.1.2

### ISSUE THREAD

**Issue by cerasmus-booking** [datastax/cassandra-quarkus#207]
We are in the process of adding Quarkus extensions that include using Cassandra. However, our extensions are already on Quarkus 2.7.x and we will need to wait for the latest Quarkus Cassandra extension release.

The main problem is that using Quarkus 2.7 does not compile since there was a library change for `quarkus-vertx`:

```
[INFO] --- quarkus-bootstrap-maven-plugin:2.7.1.Final:extension-descriptor (default) @ booking-cassandra ---
Downloading from default: https://jfrog.booking.com/artifactory/maven/com/booking/quarkus/booking-cassandra-deployment/1.0.6-SNAPSHOT/maven-metadata.xml[ERROR] Quarkus Extension Dependency Verification Error[ERROR] The deployment artifact com.booking.quarkus:booking-cassandra-deployment::jar depends on the following Quarkus extension deployment artifacts whose corresponding runtime artifacts were not found among the dependencies of com.booking.quarkus:booking-cassandra:jar:1.0.6-SNAPSHOT:
[ERROR]  com.booking.quarkus:booking-cassandra-deployment:jar:1.0.6-SNAPSHOT
[ERROR]    com.datastax.oss.quarkus:cassandra-quarkus-client-deployment:jar:1.1.1
[ERROR] *    io.quarkus:quarkus-vertx-core-deployment:jar:2.1.0.Final
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Quarkus - Booking Extensions - parent 1.0.6-SNAPSHOT:
[INFO] 
[INFO] Quarkus - Booking Extensions - parent .............. SUCCESS [  0.425 s]
[INFO] Quarkus - Booking Cassandra - Parent ............... SUCCESS [  0.012 s]
[INFO] Quarkus - Booking Cassandra - Runtime .............. FAILURE [ 12.936 s]
[INFO] Quarkus - Booking Cassandra - Deployment ........... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.658 s
[INFO] Finished at: 2022-02-18T10:14:52+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-bootstrap-maven-plugin:2.7.1.Final:extension-descriptor (default) on project booking-cassandra: The deployment artifact com.booking.quarkus:booking-cassandra-deployment::jar depends on the following Quarkus extension deployment artifacts whose corresponding runtime artifacts were not found among the dependencies of com.booking.quarkus:booking-cassandra:jar:1.0.6-SNAPSHOT: io.quarkus:quarkus-vertx-core-deployment::jar -> [Help 1]
```

Pom:
```
<dependency>
    <groupId>io.quarkus.platform</groupId>
    <artifactId>quarkus-cassandra-bom</artifactId>
    <version>2.7.1.Final</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
```

I managed to compile a Cassandra Quarkus `1.1.2-SNAPSHOT` and have it successfully compile our extension. It looks like all that is needed is the `1.1.2` release. If not, do you have a roadmap for when releases will be made?

Verions:
Quarkus: 2.7.1.Final
Maven: 3.8.4
Java: 17.0.2

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/QUAR-111) by [Unito](https://www.unito.io)

**Comment by adutra** [comment]
Hi @cerasmus-booking thanks for reporting this issue.

The incriminated artifact is `io.quarkus:quarkus-vertx-core-deployment` and it has been removed in Quarkus 2.3. It has been replaced with `io.quarkus:quarkus-vertx-deployment`.

In the Cassandra extension, we updated out `main` branch accordingly, see https://github.com/datastax/cassandra-quarkus/commit/b1ffa41ea19ee223957423584f1a54f3545b2a57. But indeed we didn't release it yet.

You probably built the Cassandra extension using an old commit. Would you mind retrying with the latest commit from main? We fixed a somewhat related issue with `quarkus-vertx` recently, see #204. You might be luckier trying that out.

As for the release, yes, we are going to release in the next days or so. Stay tuned!

**Comment by cerasmus-booking** [comment]
Hi @adutra , do you have a release date yet for `1.1.2`?

**Comment by adutra** [comment]
Hi, 1.1.2 has just been released. Thanks!
