### ISSUE TITLE
Update (quickstart guide) to recent extension / Quarkus version

### ISSUE THREAD

**Issue by Alexander-Krause-Glau** [datastax/cassandra-quarkus#212]
I think Github Discussions are not enabled for this repo, therefore, I write this issue. Are there any plans to update this extension to a recent Quarkus version? I changed the Quarkus version in your `pom.xml` and get a lot of errors. 

I come up with this because of an issue that I have in my application. After updating, I get 

`
java.lang.IllegalArgumentException: Found no registered MapperResultProducer that can produce io.smallrye.mutiny.Uni<Void>
`

for the insert operation of my DAO.

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/QUAR-114) by [Unito](https://www.unito.io)

**Comment by adutra** [comment]
Hi @Alexander-Krause-Glau thanks for raising this issue. I am about to open a PR to upgrade the extension to Quarkus 2.15 and driver 4.15.

However, I am not seeing the error you mentioned. Do you have a small reproducible test case? Thanks!

**Comment by Alexander-Krause-Glau** [comment]
Hi @adutra, 

thank you for your response. Here are some details to reproduce this (with our OSS):

1. Clone [our tool](https://github.com/ExplorViz/landscape-service) and checkout the `fix-int-test-old-approach`.
2. Run `./gradlew assemble integrationTest` to run our narrow integrationtests. This should result in the mentioned error (among others).

I saw the application code for your integration tests and thought that there might be something wrong with the code above. I tried to rebuild your [@Mapper interface](https://github.com/datastax/cassandra-quarkus/blob/main/integration-tests/application/src/main/java/com/datastax/oss/quarkus/tests/mapper/InventoryMapper.java) and the approach on a [different branch](https://github.com/ExplorViz/landscape-service/blob/dfc59ba7022a5efc9436b397611544ad337b7405/src/main/java/net/explorviz/landscape/persistence/cassandra/dao/SpanStructureMapper.java), but when executing `./gradlew clean assemble` I now receive 

```
Invalid return type: DaoFactory methods must return a Dao-annotated interface, or future thereof
```

I thought that there might be a problem with my [DI producer](https://github.com/ExplorViz/landscape-service/blob/fix-int-tests/src/main/java/net/explorviz/landscape/persistence/cassandra/dao/SpanStructureDaoProducer.java), but I couldn't find a counterpart in your integration tests or the Quarkus Cassandra guide. I remember that there was such a part in guide in the past and found it in an old commit: https://github.com/datastax/cassandra-quarkus/commit/b7e3615cf903497c6331933743456b74e6b8ff05

So, I also deleted the Producer and created a new branch: https://github.com/ExplorViz/landscape-service/tree/fix-int-tests-without-producer

Running `./gradlew clean assemble` results in the same `Invalid return type...` error. Can you see what I am doing wrong?

**Comment by Alexander-Krause-Glau** [comment]
Hi @adutra ,

today I saw that you added a new dependency in the linked commit. Adding the following to my Gralde project 

`annotationProcessor group: 'com.datastax.oss.quarkus', name: 'cassandra-quarkus-mapper-processor', version: '1.1.2'` fixed the problem (when using the "new approach" for the `ReactiveService`, i.e., using `Uni<ReactiveService>`).

However, this new approach is not documented in the Quickstart guide, right? I am not sure why I should use `Uni<ReactiveService>` instead of `ReactiveService`. I updated the title of the issue a little bit.

**Comment by adutra** [comment]
@Alexander-Krause-Glau I think I see the issue.

It seems you are not using the cassandra-quarkus-mapper-processor to generate the mapper classes, instead you are using java-driver-mapper-processor. The driver's annotation processor cannot generate Quarkus-specific stuff, such as bean producers, or beans of type `Uni`. For that, you need to use the Quarkus Cassandra mapper processor.

See here:

https://github.com/ExplorViz/landscape-service/blob/2a2894912ecc38aa26b304b7152370cf914e019b/build.gradle#L64

Change that line to:

```gradle
  annotationProcessor group: 'com.datastax.oss.quarkus', name: 'cassandra-quarkus-mapper-processor', version: "${quarkusCassandraPlatformVersion}"
```

Let me know if that helps.

**Comment by adutra** [comment]
But yes, the right mapper annotation processor to use is indeed not mentioned in the quickstart guide, I will update it.

**Comment by Alexander-Krause-Glau** [comment]
Thank you ! Let's keep this issue open so that you can reference it in your PR.
