### ISSUE TITLE
[JAVA-2778] Split classes into api and internal packages

### ISSUE THREAD

**Issue by adutra** [datastax/cassandra-quarkus#27]
<p>Imported from <a href="https://datastax-oss.atlassian.net/browse/JAVA-2778">JAVA-2778</a>, originally reported by @tomekl007 on Fri, 15 May 2020 10:43:00 GMT.</p>
<hr />
<p>We have internal classes like for example QuarkusSessionBuilder, MicroProfileMetricsUpdater, and others. <br> They are and should reside in the runtime module. The problem is that this module is imported in the client application and all classes from runtime are accessible to the client app. </p> 
<p>We should at least move those classes to the internal package to signal that they should not be used in the client code. On the other hand, public classes should be moved to api package.</p> 
<p>The second problem that should be solved in this task is to find a reason why the CassandraClientConfig and CassandraClientConnectionConfig must be in the com.datastax.oss.quarkus.config and not in the com.datastax.oss.quarkus.runtime.config. Currently, with such change, they are not visible in the deployment module. We should fix it and move those classes to com.datastax.oss.quarkus.runtime.config if possible.</p>

**Comment by tomekl007** [comment]
More info: https://github.com/datastax/cassandra-quarkus/issues/62
