### ISSUE TITLE
[JAVA-2761] Improve in-tree documentation

### ISSUE THREAD

**Issue by adutra** [datastax/cassandra-quarkus#34]
<p>Imported from <a href="https://datastax-oss.atlassian.net/browse/JAVA-2761">JAVA-2761</a>, originally reported by @tomekl007 on Tue, 5 May 2020 12:36:05 GMT.</p>
<hr />
<p>Improve the contents of in-tree documentation:</p> 
<ol> 
 <li>main README.md: currently contain developer-oriented content, should contain instead an overview of the project, where to download, where to find documentation, and a 5-minutes tutorial.</li> 
 <li>CONTRIBUTING.md: include guidelines for contributing code (branching model, code formatting, etc.);</li> 
 <li>Other README files: improve contents with module descriptions.</li> 
</ol>

**Comment by adutra** [comment]
<p>Link imported from Jira: this issue (<a href="https://datastax-oss.atlassian.net/browse/JAVA-2761">JAVA-2761</a>) --- <em>relates to</em> ---> <a href="https://datastax-oss.atlassian.net/browse/JAVA-2684">JAVA-2684</a> (<a href="https://github.com/datastax/cassandra-quarkus/issues/51">issue #51</a>).</p>

**Comment by polandll** [comment]
Make sure to ping me for any docs assistance, if you need editing or writing.

**Comment by tomekl007** [comment]
>  and a 5-minutes tutorial.
@adutra Could you explain what do you mean by 5-minutes tutorial?

> 3. Other README files: improve contents with module descriptions.
What do you mean by module descriptions?

**Comment by adutra** [comment]
> @adutra Could you explain what do you mean by 5-minutes tutorial?

I would like the main README to look like the Java driver's: How to get the extension (Maven coordinates), Compatibility / Minimum software required, Useful links, License.

Since we now have a quickstart guide, the "5-minutes tutorial" could acutally be just a link to the quickstart in the Useful Links section.

> What do you mean by module descriptions?

Each Maven submodule should have a README file describing what the submodule does – especially deployment and runtime.

**Comment by tomekl007** [comment]
1. Did we decide where the docs should be hosted (adoc file)? Will it be on the DataStax website or at the quarkus site?
2. Should we point users to our mailing list:
```
[Mailing list]: https://groups.google.com/a/lists.datastax.com/forum/#!forum/cassandra-quarkus
```
Or quarkus ML?

**Comment by adutra** [comment]
> Did we decide where the docs should be hosted (adoc file)? Will it be on the DataStax website or at the quarkus site?

It's going to be on Quarkus website, but we don't know the details. For now we don't know what to do with the adoc file. This is one of the reasons why we need at least some decent documentation in-tree.

> Should we point users to our mailing list:
[Mailing list]: https://groups.google.com/a/lists.datastax.com/forum/#!forum/cassandra-quarkus

This list doesn't exist. You can point them to the Quarkus ML for now.

**Comment by tomekl007** [comment]
I think I found a good solution for hosting adoc for now. We can just leverage the github view:
https://github.com/datastax/cassandra-quarkus/blob/master/documentation/src/main/asciidoc/cassandraclient.adoc
until it will be hosted somewhere, see the PR for more info
