### ISSUE TITLE
[JAVA-2752] Create maven archetype for generating client app that uses quarkus-extension

### ISSUE THREAD

**Issue by adutra** [datastax/cassandra-quarkus#36]
<p>Imported from <a href="https://datastax-oss.atlassian.net/browse/JAVA-2752">JAVA-2752</a>, originally reported by @tomekl007 on Mon, 27 Apr 2020 06:48:41 GMT.</p>
<hr />
<p>It should allow clients to do:<br> <a href="https://quarkus.io/guides/mongodb#creating-the-maven-project" rel="nofollow">https://quarkus.io/guides/mongodb#creating-the-maven-project</a></p>

**Comment by tomekl007** [comment]
Probably https://github.com/datastax/cassandra-quarkus/issues/119 will supersede this mechanism so maybe this doesn't need to be implemented

**Comment by adutra** [comment]
See also https://github.com/datastax/cassandra-quarkus/issues/132.

**Comment by adutra** [comment]
Closing, there is now other ways to generate a fully-working project with the Quarkus Maven plugin:

```
mvn io.quarkus:quarkus-maven-plugin:{quarkus-version}.Final:create \
-DprojectGroupId=org.acme \
-DprojectArtifactId=cassandra-quickstart \
-Dextensions="cassandra-quarkus-client,resteasy,resteasy-jackson,resteasy-mutiny,smallrye-health"
```
