### ISSUE TITLE
[JAVA-2734] Implement HdrHistogram compatible with MicroProfile

### ISSUE THREAD

**Issue by adutra** [datastax/cassandra-quarkus#40]
<p>Imported from <a href="https://datastax-oss.atlassian.net/browse/JAVA-2734">JAVA-2734</a>, originally reported by @tomekl007 on Thu, 9 Apr 2020 10:13:05 GMT.</p>
<hr />
<p>After <a href="https://datastax-oss.atlassian.net/browse/JAVA-2694" rel="nofollow">https://datastax-oss.atlassian.net/browse/JAVA-2694</a> we re-implemented the metrics to work with MicroProfile. </p> 
<p>The MicroProfileMetricsUpdater.initializeTimer method was simplified, and the current does not use custom HdrHistogram implementation and ignores driver parameters that control that, ie:</p>  
<pre>DefaultDriverOption.METRICS_SESSION_CQL_REQUESTS_HIGHEST,
DefaultDriverOption.METRICS_SESSION_CQL_REQUESTS_DIGITS,
DefaultDriverOption.METRICS_SESSION_CQL_REQUESTS_INTERVAL);</pre>  
<p>We should re-implement the HdrHistogram in the MicroProfile to keep the optimized logic.</p> 
<p>We can use TimerImpl class that takes the Reservoir as an argument. The Reservoir should be implemented with a custom logic that mimics the HdrHistogram from java-driver.</p>

**Comment by adutra** [comment]
This should wait for [JAVA-2808](https://datastax-oss.atlassian.net/browse/JAVA-2808).

**Comment by tomekl007** [comment]
This should be implemented in the driver
