### ISSUE TITLE
[JAVA-2708] Add IT tests of Cassandra extension to quarkus-platform

### ISSUE THREAD

**Issue by adutra** [datastax/cassandra-quarkus#44]
<p>Imported from <a href="https://datastax-oss.atlassian.net/browse/JAVA-2708">JAVA-2708</a>, originally reported by @tomekl007 on Thu, 26 Mar 2020 15:07:57 GMT.</p>
<hr />
<p>We decided to maintain Cassandra’s extension in our Datastax GitHub repository.</p> 
<p>According to this:<br> <a href="https://groups.google.com/d/msg/quarkus-dev/w3iMtq2L_Lw/Zo-4KwQTBgAJ" rel="nofollow">https://groups.google.com/d/msg/quarkus-dev/w3iMtq2L_Lw/Zo-4KwQTBgAJ</a></p> 
<blockquote>
 <p>There is a high probability we will want to integrate your TS (primarily smoke tests) into our platform TS (like Camel Quarkus and others do in <a href="https://github.com/quarkusio/quarkus-platform)." rel="nofollow">https://github.com/quarkusio/quarkus-platform).</a> To be able to do that the tests would have to be available as Maven artifacts.</p>
</blockquote> 
<p>We (or quarkus) team should integrate our Integration Tests into their platform. <br> To do so, we need to create a module with tests (similar to this):<br> <a href="https://github.com/apache/camel-quarkus/tree/master/integration-tests/mongodb/src/test/java/org/apache/camel/quarkus/component/mongodb/it" rel="nofollow">https://github.com/apache/camel-quarkus/tree/master/integration-tests/mongodb/src/test/java/org/apache/camel/quarkus/component/mongodb/it</a> </p> 
<p>and add them to quarkus-platform:</p> 
<p><a href="https://github.com/quarkusio/quarkus-platform/blob/master/integration-tests/camel/camel-mongodb/pom.xml#L33" rel="nofollow">https://github.com/quarkusio/quarkus-platform/blob/master/integration-tests/camel/camel-mongodb/pom.xml#L33</a> </p> 
<p>using camel.</p> 
<p>We can use our existing quarkus tests from cassandra-client extension:</p> 
<ul> 
 <li>ProductResourceTest</li> 
 <li>ProductResourceNativeTest</li> 
 <li>CassandraTestResource</li> 
</ul>

**Comment by adutra** [comment]
<p>Imported from <a href="https://datastax-oss.atlassian.net/browse/JAVA-2708?focusedCommentId=52655">JAVA-2708</a>, originally commented by @tomekl007 on Fri, 29 May 2020 06:35:17 GMT.</p>
<hr />
<p>@absurdfarce I see that you have assigned this task to yourself. What is the status of it?</p>

**Comment by absurdfarce** [comment]
@tomekl007 I planned on working this ticket after I finished the review of SPARKC-590

**Comment by absurdfarce** [comment]
Assuming joining Quarkus Platform will make us available as an option on code.quarkus.io... it would be nice to see if we can get stats on how often our extension is selected for inclusion in bundles made at code.quarkus.io.

**Comment by absurdfarce** [comment]
After looking at this a bit more I think we should table this until a version of cassandra-quarkus has been released.  We'll want to release an integration-test artifact as part of that effort; once that's out in the wild we can reference it in the pom we add here.

**Comment by tomekl007** [comment]
Is there a way to submit a PR (maybe internal) with a SNAPSHOT version of `cassandra-quarkus` to test the integration up-front?

**Comment by adutra** [comment]
Also: can we at least make sure somehow that the integration-test artifact that will be published soon will contain enough material to be integrated into the platform _and_ have its tests properly executed?

**Comment by adutra** [comment]
Quoting Alexey from a [discussion on the ML](https://groups.google.com/d/msgid/quarkus-dev/CAKaajdA%3DWSgfRG5EhnPej3MkROtEMypfuupHLn2kBpFw3j8D2w%40mail.gmail.com): 

> To get listed on code.quarkus.io you need to be integrated into the platform https://github.com/quarkusio/quarkus-platform/
> Which means import your BOMs into the runtime and deployment platform BOMs and integrate your tests into the platform testuite (which means your tests should be resolvable as maven artifacts). Any extension except probably blaze-persistence could be an example to follow. Feel free to ping me on zulip in case you need guidance.

I suggest the following path moving forward:

1. Clone https://github.com/quarkusio/quarkus-platform/
2. Create a PR against the cloned repo
3. In the PR, import our BOMs into the runtime and deployment platform BOMs as requested.
4. In the PR, create a new module to run the integration tests ([this](https://github.com/quarkusio/quarkus-platform/tree/master/integration-tests/hazelcast-client) could serve as an example).
5. Validate the setup by running the tests with our CI farm, or locally.
6. If OK, and when the extension is released: open a PR against the original Platform repo.

Items 1-5 can be done before the release using snapshots of the extension.

**Comment by tomekl007** [comment]
@absurdfarce what is the status of this task? Do you need any help?

**Comment by absurdfarce** [comment]
@tomekl007 I've been engrossed in Scala code and haven't come back to review this yet.  Broadly speaking, however, I agree with the steps outlined by @adutra above.  Note that there may be some complexity on our side to mimic the rpkgtest stuff they're doing for testing third-party JARs using this process... but it doesn't seem like that should be too bad.

Looks like more info on rpkg tests can be found [here](https://github.com/ppalaga/rpkgtests-maven-plugin).

**Comment by tomekl007** [comment]
Do you want to continue work on that ticket, or do you want me to take it from here?

**Comment by absurdfarce** [comment]
If you have cycles available it probably makes more sense for you to take it @tomekl007.  Otherwise I'll try to take a look at it later today (Wed)

**Comment by tomekl007** [comment]
I've verified the steps and our tests are working within quarkus-platform, see:
https://github.com/riptano/quarkus-platform/pull/1
Once we will release the cassandra-quarkus extension, we should update the PR and create a PR to the quarkus-platform:
https://github.com/quarkusio/quarkus-platform/compare/master...riptano:java2708

**Comment by adutra** [comment]
@tomekl007 how did you run the steps? I'm getting this error:

```
[ERROR] Plugin org.apache.maven.plugins:maven-compiler-plugin:3.8.0-jboss-2 or one of its dependencies could not be resolved: Could not find artifact org.apache.maven.plugins:maven-compiler-plugin:jar:3.8.0-jboss-2 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

I try adding this to my settings.xml:

```
        <repository>
          <id>jboss-third-party</id>
          <name>JBoss Third Party</name>
          <releases>
            <enabled>true</enabled>
            <updatePolicy>never</updatePolicy>
            <checksumPolicy>warn</checksumPolicy>
          </releases>
          <snapshots>
            <enabled>false</enabled>
            <updatePolicy>always</updatePolicy>
            <checksumPolicy>fail</checksumPolicy>
          </snapshots>
          <url>https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/</url>
          <layout>default</layout>
        </repository>
```

But I'm still seeing build failures.

**Comment by tomekl007** [comment]
Just `mvn clean verify` works for me.

**Comment by adutra** [comment]
Ok got it working. Had to add this:

```
      <pluginRepositories>
        <pluginRepository>
          <id>jboss-third-party</id>
          <name>JBoss Third Party</name>
          <releases>
            <enabled>true</enabled>
            <updatePolicy>never</updatePolicy>
            <checksumPolicy>warn</checksumPolicy>
          </releases>
          <snapshots>
            <enabled>false</enabled>
            <updatePolicy>always</updatePolicy>
            <checksumPolicy>fail</checksumPolicy>
          </snapshots>
          <url>https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/</url>
          <layout>default</layout>
        </pluginRepository>
      </pluginRepositories>
```

**Comment by adutra** [comment]
Unfortunately the alpha1 release was cut today, but we forgot to deploy a test-jar for the integration-tests module. We will have to cut an alpha2 to fix this.

**Comment by adutra** [comment]
I managed to deploy the test-jar after the release.

PR opened here: https://github.com/quarkusio/quarkus-platform/pull/80.

**Comment by tomekl007** [comment]
Closing because it was merged into the quarkus-platform
