### ISSUE TITLE
Cassandra Quarkus is build on Quarkus 1.3.0

### ISSUE THREAD

**Issue by UnvirtualHH** [datastax/cassandra-quarkus#57]
I've tried the current snapshot of cassandra quarkus and, after a while, I've checked that it is build on quarkus 1.3.0 and is not working with current quarkus versions like 1.4.2 or 1.5.0

Obivously there where some breaking changes, would be great if you could fix this soon, so I could extend my tests.

**Comment by adutra** [comment]
Hi @UnvirtualHH we are right now upgrading the master branch to Quarkus 1.5.0. But we've been testing our extension against 1.5.0 for a while now, and we do not see any specific problems. Could you please share with us which problems you are seeing? Thanks!

**Comment by UnvirtualHH** [comment]
Well, I've checked it again, with the current master branch it works. I was on the java2754 branch, cause I really need the reactive graph way (please also provide an example for graph!!!) and there it won't works. But I'm sure the next rebase on your side will solve it, so again I need to wait :D

**Comment by adutra** [comment]
@UnvirtualHH support for reactive has been merged to master. You can test it now, although you need to build the driver first (we are using driver 4.7.0-SNAPSHOT for now, it's not released yet).

**Comment by UnvirtualHH** [comment]
@adutra Thanks a lot. General integration works now, but there is no quickstart or example for using reactive graph available. Cause I can't use object mapper for this the quickstart approach by using dao and mapper is not possible. Or did I missed something and u've extended it for graph?

So, maybe a quick example how to inject CqlSession and execute a statement to receive a ReactiveGraphResultSet? Thanks a lot.
