### ISSUE TITLE
Validate that cassandra-quarkus/runtime module does not have a dependency to quarkus-core-deployment 

### ISSUE THREAD

**Issue by tomekl007** [datastax/cassandra-quarkus#60]
When working on JAVA-2719 I was able to import the `deployment/ShutdownContextBuildItem` class in the `runtime/CassandraClientRecorder`. 
This is suspicious because the runtime module should not have quarkus deployment classes on the classpath. We should verify that `cassandra-quarkus/runtime` does not have a dependency on `quarkus-core-deployment`

**Comment by adutra** [comment]
The culprit is `quarkus-smallrye-metrics-spi`:

```
[INFO] +- io.quarkus:quarkus-smallrye-metrics-spi:jar:1.5.0.Final:compile
[INFO] |  \- io.quarkus:quarkus-core-deployment:jar:1.5.0.Final:compile
```
