### ISSUE TITLE
Clarify usage of log frameworks

### ISSUE THREAD

**Issue by adutra** [datastax/cassandra-quarkus#70]
Right now we claim to use SLF4J only. It is indeed our logging API but:

1. We don't declare it in any pom, so it gets pulled transitively from the driver. We need to explicitly declare this dependency where appropriate.
2. In some places, we are using the JBoss logging backed directly, e.g. in `CassandraTestResource`. We should change that. It might also be a good thing, for correctness, to also declare a runtime dependency on that backend.

_Originally posted by @adutra in https://github.com/datastax/cassandra-quarkus/pull/67/files_

**Comment by adutra** [comment]
We also added recently this dependency to the quickstart:

```
<dependency>
      <groupId>org.jboss.logging</groupId>
      <artifactId>commons-logging-jboss-logging</artifactId>
      <scope>runtime</scope>
    </dependency>
```

**Comment by tomekl007** [comment]
It seems that we cannot use Log4J because it is banned dependency in the quarkus, see:
```
<!-- Ban Log4J (use org.jboss.logmanager:log4j-jboss-logmanager instead) -->
<exclude>log4j:log4j</exclude>
<exclude>org.apache.logging.log4j:log4j-api</exclude>
<exclude>org.apache.logging.log4j:log4j-core</exclude>
<exclude>org.apache.logging.log4j:log4j-slf4j-impl</exclude>
```
Instead of this, the logger should be defined like this:
```
import org.jboss.logging.Logger;

private static final Logger LOGGER = Logger.getLogger(GrpcClientProcessor.class.getName());
```

**Comment by tomekl007** [comment]
We are allowed to use log4j so this issue can be closed
