### ISSUE TITLE
Add config settings for keyspace and graph name

### ISSUE THREAD

**Issue by UnvirtualHH** [datastax/cassandra-quarkus#72]
Just as a feedback for your actual work. I'm using the snapshot of the quarkus-cassandra driver and use it for graph statements. It is actually working, but I have to set the graph name on every statement, cause the property quarkus.cassandra.graph.name is ignored. Such "Standart" properties should be supported.

**Comment by tomekl007** [comment]
Hello, currently we do not expose this property using `quarkus.cassandra` prefix.
If you want to tweak this setting, you need to create an `application.conf` or `application.json` with this setting and put it in the `/resources`. Once it is on the classpath, it will be automatically picked by the `QuarkusCqlSession`, please see docs:
https://github.com/datastax/cassandra-quarkus/blob/6a7ecd047e48d6eaf7e5a806977b107c5cd6c537/documentation/src/main/asciidoc/cassandraclient.adoc#configuring-the-cassandra-database

**Comment by UnvirtualHH** [comment]
Yes, It was just a feature request or a nice to have. Application.conf is a known way, but I would prefer to have all the config at one place.

**Comment by adutra** [comment]
All things considered, I think we can include both the keyspace name and the graph name in the config.
