### ISSUE TITLE
Double-check driver dependency exclusions

### ISSUE THREAD

**Issue by adutra** [datastax/cassandra-quarkus#79]
We currently exclude a lot of driver dependencies:

```
    <dependency>
      <groupId>com.datastax.oss</groupId>
      <artifactId>java-driver-core</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.slf4j</groupId>
          <artifactId>jcl-over-slf4j</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.codehaus.groovy</groupId>
          <artifactId>groovy</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.codehaus.groovy</groupId>
          <artifactId>groovy-json</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.squareup</groupId>
          <artifactId>javapoet</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.ow2.asm</groupId>
          <artifactId>asm-util</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.dropwizard.metrics</groupId>
          <artifactId>metrics-core</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```

I'm not sure all of this is required. The following seems more appropriate, and the build passes including native tests:

```
    <dependency>
      <groupId>com.datastax.oss</groupId>
      <artifactId>java-driver-core</artifactId>
      <exclusions>
        <exclusion>
          <groupId>io.dropwizard.metrics</groupId>
          <artifactId>metrics-core</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```

It would be good to investigate what needs to be excluded, and why.

**Comment by tomekl007** [comment]
The reason why they are excluded is that they are part of the `bannedDependencies` in the quarkus:
`https://github.com/quarkusio/quarkus/blob/master/build-parent/pom.xml#L279`

If we will remove those dependencies, our build will pass but we may have a problem with CI build against the quarkus itself (this https://github.com/datastax/cassandra-quarkus/actions?query=workflow%3A%22Quarkus+ecosystem+CI%22)

**Comment by adutra** [comment]
Can we know for sure ? the pom file you linked in your comment is not a parent of our extension.

**Comment by tomekl007** [comment]
I think that we would need to run the build against https://github.com/datastax/cassandra-quarkus/actions?query=workflow%3A%22Quarkus+ecosystem+CI%22.

When I was starting creating an extension (the 1st try in the quarkus repo) I got errors because of those banned dependencies.

**Comment by adutra** [comment]
1. I don't see groovy, asm and javapoet listed among the banned dependencies, only slf4j artifacts.
3. Looking for examples, I noticed that debezium uses SLF4J but always declares SLF4J dependencies [in provided scope](https://github.com/debezium/debezium/commit/5fbe742be8aea075c1c96bedbd023aeb57397785). Maybe that's what we need to do, I will experiment with that.
2. Looking at the logs of the latest Quarkus Ecosystem CI build, and as far as I can tell, they are just building our extension after building Quarkus master. Indeed the enforcer plugin is used when building Quarkus, so if our extension was hosted there, the build would fail.
