### ISSUE TITLE
Simplify configuration properties

### ISSUE THREAD

**Issue by adutra** [datastax/cassandra-quarkus#80]
Currently to specify the local DC users have to enter the following property:

```
quarkus.cassandra.load-balancing-policy.local-datacenter=dc1
```

That's a bit too verbose, I suggest that we simplify this to `quarkus.cassandra.local-datacenter`. At this level of configuration we need to focus on simplicity, and users don't need to know that this is intended to be fed into the load balancing policy.

**Comment by adutra** [comment]
I would also change `metrics.session-enabled` to `metrics.session.enabled` and `metrics.node-enabled` to `metrics.node.enabled`.

**Comment by tomekl007** [comment]
> I would also change `metrics.session-enabled` to `metrics.session.enabled` and `metrics.node-enabled` to `metrics.node.enabled`.

For this, I would keep the original name. Adding `.` prefix doesn't seem to simplify a lot, isn't it?
Having `-` in the name keep this setting in sync with the java-driver setting.

**Comment by adutra** [comment]
> > I would also change `metrics.session-enabled` to `metrics.session.enabled` and `metrics.node-enabled` to `metrics.node.enabled`.
> 
> For this, I would keep the original name. Adding `.` prefix doesn't seem to simplify a lot, isn't it?
> Having `-` in the name keep this setting in sync with the java-driver setting.

You are right, let's not change it.
