### ISSUE TITLE
Consider making properties optional in CassandraClientConnectionConfig

### ISSUE THREAD

**Issue by adutra** [datastax/cassandra-quarkus#81]
Currently two settings are required in CassandraClientConnectionConfig: contact points and local datacenter. This may not play well if users wish to specify these elsewhere, e.g. in application.conf. Also requiring a contact point may not play well with Astra.

**Comment by adutra** [comment]
@tomekl007  why was this closed?

**Comment by tomekl007** [comment]
> @tomekl007 why was this closed?
I don't know. Maybe I've referenced this issue by mistake. I just re-opened

**Comment by adutra** [comment]
Fixed by #95.
