### ISSUE TITLE
Fix CassandraMetricsNativeIT

### ISSUE THREAD

**Issue by adutra** [datastax/cassandra-quarkus#96]
In our builds, `CassandraMetricsNativeIT` is reported successful but with zero tests:

```
[INFO] Running com.datastax.oss.quarkus.tests.CassandraMetricsNativeIT
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 s - in com.datastax.oss.quarkus.tests.CassandraMetricsNativeIT
```

However in quarkus-platform, this test fails:

```
[INFO] Running com.datastax.oss.quarkus.tests.CassandraMetricsNativeIT
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.013 s <<< FAILURE! - in com.datastax.oss.quarkus.tests.CassandraMetricsNativeIT
[ERROR] com.datastax.oss.quarkus.tests.CassandraMetricsNativeIT  Time elapsed: 0.013 s  <<< ERROR!
org.junit.platform.commons.JUnitException: @Inject is not supported in NativeImageTest tests. Offending field is com.datastax.oss.quarkus.tests.CassandraMetricsIT.cqlSession
```

It seems that we should not inject beans in native tests. A small refactoring of `CassandraMetricsIT` should bring everything back to normal: remove `cqlSession` field and trigger a query to the database inside the REST resource, not in the test class itself.

**Comment by absurdfarce** [comment]
I'm not sure it's quite that easy @adutra :(  "/metrics" is a route provided by Quarkus itself... I don't think we have much control over what actually gets executed by whatever handles that route.

**Comment by adutra** [comment]
I was thinking about doing a POST request to the `/cassandra/product/` endpoint first. That would trigger session initialization and a few queries to the database.

**Comment by absurdfarce** [comment]
Ah, that makes _significantly_ more sense then. :)

I can put together a PR for that unless you already have one in-flight.

**Comment by absurdfarce** [comment]
PR merged... let's see how the next quarkus-platform build fares.
